"""Add first_name and last_name to user

Revision ID: e80f1ac15563
Revises: xxxx
Create Date: 2026-03-24 15:54:10.396843

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e80f1ac15563"
down_revision: Union[str, Sequence[str], None] = "xxxx"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accesstoken", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accesstoken_token"))
        batch_op.drop_column("id")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("first_name", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_name", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    with op.batch_alter_table("accesstoken", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.INTEGER(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_accesstoken_token"), ["token"], unique=1
        )

    # ### end Alembic commands ###
